#############################################
# Input files to drive the pipeline
#############################################

# NOTES:
# .gz files are accepted
# provide path to genome file
fasta: /path/to/reference_genome.fa


# Path/to/readsForward1,2,3,4\n
# Path/to/readsReverse1,2,3,4\n
# Path/to/reference/genome.fasta\n
# Organism_name (just for naming)
samples_csv: /path/to/sample_information.csv

# use bwa-mem2 insted of bwa. up 2x faster algorithm but ~6x more demanding in RAM.
bwa-mem2: 'False'
# output folder name, NOT path
output: ./output

# output logs will be written to "logs" directory inside output folder
logs: ./output/logs

#####
# END of input parameters
#####



#######################
# source required tools and provide parameters
# NOTE: below tools are required for the snakemake pipeline
#######################

source:
  omni-c: " omni-c-20210720_a30d45f_CBG"
  arima: " chic-1.4_CBG"
  snakemake: " snakamake-7.12.1_CBG "
  yahs: " yahs-1.2a.2_CBG "
  seqtk: " seqtk-1.3_CBG "
  cooler: " cooler-0.9.1_CBG "
  pretext: " pretext-0.1.0_CBG  "
  minimap2: " minimap2-2.22_CBG  "

# 1 means true for the parameter and 0 means false. 
# For formatting options refer to the HiCUP documention
# https://www.bioinformatics.babraham.ac.uk/projects/hicup/read_the_docs/html/index.html
# shortest sequence is the shorthest sequence for a read after the HiCUP process 
# (they recommend 50, less than that is at the risk of a keep invalid reads)
# longest ditag is the max size you expect for a ligation event. It depends of the restriction enzimes you choose to use in the hi-c protocol.

hicup:
  keep: 1
  quiet: 0
  compress: 0
  formatting: "Illumina_1.5"
  shortest_sequence: 50
  longest_ditag: 600

# END of source tools and parameters
#####


#############################################
# Job and JIRA configurations
#############################################
# DO NOT CHANGE THIS
# prefix:
#   index_name: "genome.fa"
jira:
  # jira_id : "PPBFX-611" # An example
  jira_id : ""
  site: "http://jira.earlham.ac.uk"
  username: "tgacpap"
  password_file: "/ei/cb/common/.jira_pwd"
notify_jira: False
#############################################
# END of Job and JIRA configurations
#############################################